
[DATA_NODE.viewed]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
default_data = [ ]

[DATA_NODE.liked]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
default_data = [ ]

[DATA_NODE.disliked]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
default_data = [ ]

[DATA_NODE.recommendations_user]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
default_data = [ ]

[TASK.recommend_films_to_user]
inputs = ["liked:SECTION", "disliked:SECTION", "viewed:SECTION" ]
outputs = ["recommendations_user:SECTION"]
function = "algos.algos.recommend_films_to_user:function"
skippable = "False:bool"

[PIPELINE.pipeline]
tasks = [ "recommend_films_to_user:SECTION" ]

[SCENARIO.user]
pipelines = [ "pipeline:SECTION" ]
