[TAIPY]
read_entity_retry = "3:int"

[DATA_NODE.augmented_movies_dataset]
storage_type = "csv"
scope = "GLOBAL:SCOPE"
path = "../Downloads/ml-25m/augmented_small_movies.csv"
#path = "data/augmented_small_movies.csv"

[DATA_NODE.imdb_top_1000]
storage_type = "csv"
scope = "GLOBAL:SCOPE"
path = "../Downloads/ml-25m/IMDB_top_1000.csv"
#path = "data/IMDB_top_1000.csv"

[DATA_NODE.movie_title]
default_data = "Toy Story"

[DATA_NODE.movie_bagofwords]

[DATA_NODE.number_of_rec]
default_data = "10:int"

[DATA_NODE.recommendations]

[TASK.process_title]
function = "algos.recommender_algos.process_title:function"
inputs = [ "movie_title:SECTION", "augmented_movies_dataset:SECTION",]
outputs = [ "movie_bagofwords:SECTION",]
skippable = "False:bool"

[TASK.give_rcommendations]
function = "algos.recommender_algos.give_recommendations:function"
inputs = [ "movie_bagofwords:SECTION", "number_of_rec:SECTION", "imdb_top_1000:SECTION",]
outputs = [ "recommendations:SECTION",]
skippable = "False:bool"

[PIPELINE.pipeline]
tasks = [ "process_title:SECTION", "give_rcommendations:SECTION",]

[SCENARIO.scenario]
pipelines = [ "pipeline:SECTION",]

[SCENARIO.scenario.comparators]
